<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'SepaQr\\' => array($vendorDir . '/smhg/sepa-qr-data/src'),
);
